language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.7.2
    - ADMINER_VER=4.6.3 ADMINER_LANG=en TAGS=4.6,4,latest

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
